[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#AFF8C8"
backgroundColor = "#0F2830"
secondaryBackgroundColor = "#1A3A42"
textColor = "#E8F4F8" 